### ISSUE TITLE
bug when choosing from a list of choice all the same length

### ISSUE THREAD

**Issue by plicease** [plicease/Term-Clui#3]
Noted from the original maintainer Peter Billam:

```
A couple of weeks ago I came across a bug when choosing from a
list of choice all the same length, all about 30 chars, so two
columns on my xterm. When I was on one of the right-hand column
and pressed the UP arrow, the choice flipped into the left column
(of the previous row) when it should have stayed in the right column.
I haven't made a concentrated try to reproduce this behaviour,
but I will do, and let you know when I understand what's happening. 
```

**Comment by peterbillam** [comment]
A fix: in the KEY_UP handling of sub choose

    last if $new_mid_col < $mid_col;   # we're past it

should be

    last if $new_mid_col <= $mid_col;  # we're past or aligned with it

and likewise in the Python version
  https://github.com/plicease/Term-Clui/blob/master/py/TermClui.py

    if new_mid_col < mid_col:         # we're past it

should be

    if new_mid_col <= mid_col:  # we're past or aligned

and in the Lua version
  http://luarocks.org/modules/peterbillam/commandlineui

    if new_mid_col < mid_col then break end

is now

    if new_mid_col <= mid_col then break end

so that they handle exactly-vertically-aligned items :-)
